name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install # Sử dụng npm install vì đôi khi package-lock có thể không đồng bộ hoàn toàn
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
env:
  BASE_URL: ${{ vars.BASE_URL }}
  STANDARD_USER: ${{ vars.STANDARD_USER }}
  STANDARD_PASSWORD: ${{ vars.STANDARD_PASSWORD }}
  ADMIN_USER: ${{ vars.ADMIN_USER }}
  ADMIN_PASSWORD: ${{ vars.ADMIN_PASSWORD }}
  PROBLEM_USER: ${{ vars.PROBLEM_USER }}
  PROBLEM_PASSWORD: ${{ vars.PROBLEM_PASSWORD }}
  LOCKED_OUT_USER: ${{ vars.LOCKED_OUT_USER }}
  LOCKED_OUT_PASSWORD: ${{ vars.LOCKED_OUT_PASSWORD }}
  PERFORMANCE_GLITCH_USER: ${{ vars.PERFORMANCE_GLITCH_USER }}
  PERFORMANCE_GLITCH_PASSWORD: ${{ vars.PERFORMANCE_GLITCH_PASSWORD }}
  ERROR_USER: ${{ vars.ERROR_USER }}
  ERROR_PASSWORD: ${{ vars.ERROR_PASSWORD }}
  VISUAL_USER: ${{ vars.VISUAL_USER }}
  VISUAL_PASSWORD: ${{ vars.VISUAL_PASSWORD }}

